name: Build and upload Docker image
on:
  push:
    branches:
      - master

jobs:

  define-matrix:
    name: Define output variables which are shared across jobs
    runs-on: ubuntu-latest

    outputs:
      build_types: ${{ steps.build_types.outputs.build_types }}
      build_platforms: ${{ steps.build_platforms.outputs.build_platforms }}
      platform_runner: ${{ steps.platform_runner.outputs.platform_runner }}
      platform_os: ${{ steps.platform_os.outputs.platform_os }}

    steps:
      - name: Define build types
        id: build_types
        run: |
          echo 'build_types=["Debug"]' >> "$GITHUB_OUTPUT"

      - name: Define build platforms
        id: build_platforms
        run: |
          echo 'build_platforms=["linux/arm64", "linux/x86_64"]' >> "$GITHUB_OUTPUT"

      - name: Define platform runner map
        id: platform_runner
        run: |
          echo 'platform_runner={"linux/arm64": "ubuntu-24.04-arm", "linux/x86_64": "ubuntu-24.04"}' >> "$GITHUB_OUTPUT"

      - name: Define platform OS map
        id: platform_os
        run: |
          {
            cat << EOF
            platform_os={
              "linux/arm64": "Linux",
              "linux/x86_64": "Linux"
            }
            EOF
          } >> "$GITHUB_OUTPUT"

  build-and-upload:
    name: Perform build and upload image to GHCR
    needs:
      - define-matrix

    strategy:
      fail-fast: true
      matrix:
        build_type: ${{ fromJSON(needs.define-matrix.outputs.build_types) }}
        build_platform: ${{ fromJSON(needs.define-matrix.outputs.build_platforms) }}

    env:
      PLATFORM: ${{ matrix.build_platform }}

    runs-on: ${{ needs.define-matrix.outputs.platform_runner[env.PLATFORM] }}

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Configure timbre build system
        run: |
          cmake -B build \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
            -DENABLE_DOCKER_BUILD=TRUE \
            -DDISABLE_LOCAL_BUILD=TRUE \
            -DDOCKER_REGISTRY=localhost:5000/ \
            -DDOCKER_PLATFORM_ID=${{ matrix.build_platform }}

      - name: Build timbre image locally
        run: cmake --build build -t build_docker_image

      - name: Push image to GHCR
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/msfrank/timbre/${{ matrix.build_platform }}/${{ matrix.build_type }}:latest \
            localhost:5000/timbre:latest