name: Build and upload Docker image
on:
  push:
    branches:
      - master

jobs:
  build-and-upload:
    name: Perform build and upload image to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build timbre image locally
        run: |
          cmake -B build
          cmake --build -t build_docker_image

      - name: Push image to GHCR
        run: docker buildx imagetools create --tag ghcr.io/msfrank/timbre:latest msfrank/timbre:latest