name: Build and upload Docker image
on:
  push:
    branches:
      - master

jobs:
  build-and-upload:
    name: Perform build and upload image to GHCR
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/x86_64
          - linux/arm64

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Configure timbre build system
        run: |
          cmake -B build \
            -DENABLE_DOCKER_BUILD=TRUE \
            -DDISABLE_LOCAL_BUILD=TRUE \
            -DDOCKER_REGISTRY=localhost:5000 \
            -DDOCKER_PLATFORM_ID=${{matrix.platform}}

      - name: Build timbre image locally
        run: cmake --build build -t build_docker_image

      - name: Push image to GHCR
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/msfrank/timbre:latest \
            localhost:5000/timbre/timbre:latest